/**:
  ros__parameters:
    # --------------------------------------------------
    # 1. フレーム & TF設定
    # --------------------------------------------------
    global_frame_id: "map"
    odom_frame_id: "odom"
    base_frame_id: "base_link"
    footprint_frame_id: "base_link"
    tf_broadcast: true                  # map -> odom の TF を発行するかどうか

    # --------------------------------------------------
    # 2. トピック名
    # --------------------------------------------------
    scan_topic: "merged_scan"           # 受信するLiDARのトピック名

    # --------------------------------------------------
    # 3. パーティクル & 処理負荷
    # --------------------------------------------------
    num_particles: 1200                  # パーティクルの総数
    scan_increment: 1                   # スキャンデータの間引き（1=全データ使用）
    odom_freq: 37
    # --------------------------------------------------
    # 4. 膨張リセット（EMCL固有）のチューニング
    # --------------------------------------------------
    alpha_threshold: 0.03                 # 尤度の閾値（下回ると膨張リセット発動）
    expansion_radius_position: 0.1       # 位置の分散半径 [m]
    expansion_radius_orientation: 0.2    # 角度の分散範囲 [rad]

    # --------------------------------------------------
    # 5. センサモデル（LiDAR）設定
    # --------------------------------------------------
    laser_min_range: 0.05               # 近距離ノイズ除去のため0.05mに推奨変更
    laser_max_range: 15.0               # 最大有効距離 [m]
    likelihood_max_dist: 1.0            # 尤度場計算の最大距離 [m]

    # --------------------------------------------------
    # 6. 移動モデル（オドメトリノイズ）設定
    # --------------------------------------------------
    fw_dev: 0.10                        # 直進方向の誤差標準偏差 [m/m]
    rot_dev: 0.20                       # 回転方向の誤差標準偏差 [rad/rad]
    side_dev: 0.05                      # 横移動（全方位移動時）の誤差標準偏差 [m/m]

    # --------------------------------------------------
    # 7. 初期位置設定
    # --------------------------------------------------
    initial_pose_x: 0.4
    initial_pose_y: -4.0
    initial_pose_a: -1.5708         # 初期向き（Yaw角 [rad]）

    # -----------------------------
    # initial_pose_x: 0.4
    # initial_pose_y: -4.0
    # initial_pose_a: -1.5708